// Zustand slices, one per feature — UI/session state only, never persisted
// domain data directly (reads/writes go through domain repository interfaces)

export { useGoalStore } from './goalStore'
export { useDailyEntryStore } from './dailyEntryStore'
export { useThemeStore } from './themeStore'
export type { Mood, ColorScheme } from './themeStore'
export { useUnitStore } from './unitStore'
export type { Unit } from './unitStore'
export { useMealItemStore } from './mealItemStore'
export { useGoalCelebrationStore } from './goalCelebrationStore'
export { useCycleTrackingStore } from './cycleTrackingStore'
export { useDigestionTrackingStore } from './digestionTrackingStore'
export { useWaterTrackingStore } from './waterTrackingStore'
export { useWeekStartStore } from './weekStartStore'
export type { WeekStart } from './weekStartStore'
export { useFoodOverrideStore } from './foodOverrideStore'
export { useMealLabelPresetStore } from './mealLabelPresetStore'
export { useDailyReminderStore } from './dailyReminderStore'
export { useCustomChartSelectionStore } from './customChartSelectionStore'
export type { ChartSeriesType } from './customChartSelectionStore'
export { useAddMealRowCollapseStore } from './addMealRowCollapseStore'
export { useTrendChartSeriesStore } from './trendChartSeriesStore'
export type { TrendChartKey, TrendSeriesKey } from './trendChartSeriesStore'
export { useDashboardChartVisibilityStore } from './dashboardChartVisibilityStore'
export type { DashboardChartKey } from './dashboardChartVisibilityStore'
export { useTrackedFieldsStore } from './trackedFieldsStore'
export type { TrackedField } from './trackedFieldsStore'
export { useSectionVisibilityStore } from './sectionVisibilityStore'
export type { SectionKey } from './sectionVisibilityStore'
export { useProfileStore } from './profileStore'
export type { ActivityLevel, Sex } from './profileStore'
export { useBodyCompositionSelectionStore } from './bodyCompositionSelectionStore'
