// Shared React hooks
export { useGoalCoveringDate } from './useGoalCoveringDate'
export { useActiveGoalProgress } from './useActiveGoalProgress'
export { useAppUpdateAvailable } from './useAppUpdateAvailable'
export { useOnlineStatus } from './useOnlineStatus'
export { useIsTextInputFocused } from './useIsTextInputFocused'
export { useVisualViewportShrunk } from './useVisualViewportShrunk'
export { usePullToRefresh } from './usePullToRefresh'
export { useMaxRecordedWeight } from './useMaxRecordedWeight'
export { useLatestWeight } from './useLatestWeight'
export { usePastGoals } from './usePastGoals'
export { usePreviousDayEntry } from './usePreviousDayEntry'
export { useEntryFieldComparisonBaselines } from './useEntryFieldComparisonBaselines'
export type { EntryFieldComparisonBaselines } from './useEntryFieldComparisonBaselines'
export { useDebouncedValue } from './useDebouncedValue'
export { useWeeklyGoalCelebration } from './useWeeklyGoalCelebration'
export { useWeekStartsOn } from './useWeekStartsOn'
export { useOutlierExclusion } from './useOutlierExclusion'
export { useNearViewport } from './useNearViewport'
